Traceback (most recent call last):
  File "/home/bingxing2/ailab/wangkuncan/soft/l1/./scripts/data/generate_mmlu.py", line 3, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
